stages:
    - deploy_alpha
deploy:
    stage:
        deploy_alpha
    only:
        - feature
    script:
        - sshpass -p "$ADMINPASS" rsync -avh * admin@13.115.96.40:/var/www/html/iscar_pm/
        - sshpass -p "$ADMINPASS" ssh admin@13.115.96.40 'sudo chown -R apache.apache /var/www/html/iscar_pm;sudo chmod -R 755 /var/www/html/iscar_pm;sudo chmod -R 777 /var/www/html/iscar_pm/storage;'